version: '3.8'

services:
  user-service:
    build:
      context: ./backend/user_service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
  
  product-service:
    build:
      context: ./backend/product_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
  order-service:  
    build:
      context: ./backend/order_service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - user-service
      - product-service
      - order-service
    environment:
      REACT_APP_API_URL: http://localhost:5000