services:
  user-service:
    build:
      context: ./backend/user_service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      postgres_user:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5433/user_database
  
  product-service:
    build:
      context: ./backend/product_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      postgres_product:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5434/product_database  
  order-service:  
    build:
      context: ./backend/order_service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - product-service
      - order-service
    environment:
      REACT_APP_PRODUCT_URL: http://localhost:5001
      REACT_APP_USER_URL: http://localhost:5002
      REACT_APP_ORDER_URL: http://localhost:5003 

  postgres_user:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_database
    ports:
      - "5433:5432"
    volumes:
      - user_database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres_product:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product_database
    ports:
      - "5434:5432"
    volumes:
      - product_database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    
volumes:
  product_database:
  user_database:
  
  