# This is a GitHub Actions workflow file for a CI/CD pipeline.
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  install-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Verify Docker Compose
        run: docker-compose --version

  build-database:
    runs-on: ubuntu-latest
    needs: install-docker
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build Postgres database for User Service
        run: docker-compose build postgres_user

      - name: Build Postgres database for Product Service
        run: docker-compose build postgres_product

  build-backend:
    runs-on: ubuntu-latest
    needs: build-database
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build User Service Backend
        run: docker-compose build user-service

      - name: Build Product Service Backend
        run: docker-compose build product-service

      - name: Build Order Service Backend
        run: docker-compose build order-service

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build Frontend
        run: docker-compose build frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Deploy to Production
        run: docker-compose up -d
